package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bonus generated by hbm2java
 */
@Entity
@Table(name = "blacklist")
public class BlackList implements java.io.Serializable {


	private int id;
	
    private String telephone;
    
    private String uname;
    
    private int project;

    @Id
    @Column(name = "id", unique = true, nullable = false, precision = 65, scale = 30)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "uname")
	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "project")
	public int getProject() {
		return project;
	}

	public void setProject(int project) {
		this.project = project;
	}

    
}


