package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * Bonus generated by hbm2java
 */
@Entity
@Table(name = "BONUS")
public class Bonus implements java.io.Serializable {


    private BonusId id;

    public Bonus() {
    }

    public Bonus(BonusId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "ename", column = @Column(name = "ENAME", length = 10)),
            @AttributeOverride(name = "job", column = @Column(name = "JOB", length = 9)),
            @AttributeOverride(name = "sal", column = @Column(name = "SAL", precision = 65, scale = 30)),
            @AttributeOverride(name = "comm", column = @Column(name = "COMM", precision = 65, scale = 30))})
    public BonusId getId() {
        return this.id;
    }

    public void setId(BonusId id) {
        this.id = id;
    }


}


