package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * CliPartake generated by hbm2java
 */
@Entity
@Table(name = "cliPartake")
public class CliPartake implements java.io.Serializable {


    private Integer id;
    private Integer eid;
    private Integer uid;
    private String uname;
    private String telephone;
    private Integer region;
    private Integer project;
    private Date ptime;
    private Date audittime;

    public CliPartake() {
    }


    public CliPartake(Integer id, Integer eid, Integer uid, String uname, Integer project) {
        this.id = id;
        this.eid = eid;
        this.uid = uid;
        this.uname = uname;
        this.project = project;
    }

    public CliPartake(Integer id, Integer eid, Integer uid, String uname, String telephone, Integer region, Integer project, Date ptime, Date audittime) {
        this.id = id;
        this.eid = eid;
        this.uid = uid;
        this.uname = uname;
        this.telephone = telephone;
        this.region = region;
        this.project = project;
        this.ptime = ptime;
        this.audittime = audittime;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, precision = 65, scale = 30)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "eid", nullable = false, precision = 65, scale = 30)
    public Integer getEid() {
        return this.eid;
    }

    public void setEid(Integer eid) {
        this.eid = eid;
    }

    @Column(name = "uid", nullable = false, precision = 65, scale = 30)
    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    @Column(name = "uname", nullable = false, length = 50)
    public String getUname() {
        return this.uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    @Column(name = "telephone", length = 11)
    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    @Column(name = "region", precision = 65, scale = 30)
    public Integer getRegion() {
        return this.region;
    }

    public void setRegion(Integer region) {
        this.region = region;
    }

    @Column(name = "project", nullable = false, precision = 65, scale = 30)
    public Integer getProject() {
        return this.project;
    }

    public void setProject(Integer project) {
        this.project = project;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ptime", length = 19)
    public Date getPtime() {
        return this.ptime;
    }

    public void setPtime(Date ptime) {
        this.ptime = ptime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "audittime", length = 19)
    public Date getAudittime() {
        return this.audittime;
    }

    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }


}


