package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * CliReadilyTakePost generated by hbm2java
 */
@Entity
@Table(name = "cliReadilyTakePost")
public class CliReadilyTakePost implements java.io.Serializable {


    private Integer id;
    private Integer rid;
    private Integer uid;
    private String uname;
    private String telephone;
    private Integer region;
    private Integer project;
    private String title;
    private Integer hit;
    private Integer cnmu;
    private String content;
    private Date uptime;
    private Date audittime;
    private Integer status;
    private String pictures;
    private String smallpic;
    private Integer praisenum;
    private Integer reportnum;

    public CliReadilyTakePost() {
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "CliReadilyTakePost [id=" + id + ", rid=" + rid + ", uid=" + uid
				+ ", uname=" + uname + ", telephone=" + telephone + ", region="
				+ region + ", project=" + project + ", title=" + title
				+ ", hit=" + hit + ", cnmu=" + cnmu + ", content=" + content
				+ ", uptime=" + uptime + ", audittime=" + audittime
				+ ", status=" + status + ", pictures=" + pictures
				+ ", smallpic=" + smallpic + ", praisenum=" + praisenum
				+ ", reportnum=" + reportnum + "]";
	}






	@Id
    @Column(name = "id", unique = true, nullable = false, precision = 65, scale = 30)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "rid", nullable = false, precision = 65, scale = 30)
    public Integer getRid() {
        return this.rid;
    }

    public void setRid(Integer rid) {
        this.rid = rid;
    }

    @Column(name = "uid", nullable = false, precision = 65, scale = 30)
    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    @Column(name = "uname", nullable = false, length = 50)
    public String getUname() {
        return this.uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    @Column(name = "telephone", length = 11)
    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    @Column(name = "region", precision = 65, scale = 30)
    public Integer getRegion() {
        return this.region;
    }

    public void setRegion(Integer region) {
        this.region = region;
    }

    @Column(name = "project", nullable = false, precision = 65, scale = 30)
    public Integer getProject() {
        return this.project;
    }

    public void setProject(Integer project) {
        this.project = project;
    }

    @Column(name = "title", nullable = false, length = 128)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "hit", precision = 65, scale = 30)
    public Integer getHit() {
        return this.hit;
    }

    public void setHit(Integer hit) {
        this.hit = hit;
    }

    @Column(name = "cnmu", precision = 65, scale = 30)
    public Integer getCnmu() {
        return this.cnmu;
    }

    public void setCnmu(Integer cnmu) {
        this.cnmu = cnmu;
    }

    @Column(name = "content", nullable = false)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "uptime", length = 19)
    public Date getUptime() {
        return this.uptime;
    }

    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "audittime", length = 19)
    public Date getAudittime() {
        return this.audittime;
    }

    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    @Column(name = "status", nullable = false, precision = 65, scale = 30)
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Column(name = "pictures", length = 65535)
    public String getPictures() {
        return this.pictures;
    }

    public void setPictures(String pictures) {
        this.pictures = pictures;
    }

    @Column(name = "smallpic", length = 65535)
    public String getSmallpic() {
        return this.smallpic;
    }

    public void setSmallpic(String smallpic) {
        this.smallpic = smallpic;
    }

    @Column(name = "praisenum", precision = 65, scale = 30)
    public Integer getPraisenum() {
        return this.praisenum;
    }

    public void setPraisenum(Integer praisenum) {
        this.praisenum = praisenum;
    }

    @Column(name = "reportnum")
	public Integer getReportnum() {
		return reportnum;
	}


	public void setReportnum(Integer reportnum) {
		this.reportnum = reportnum;
	}


}


