package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * CliReadilyTakeComment generated by hbm2java
 */
@Entity
@Table(name = "cliReadilyTakeComment")
public class CliReadilyTakeComment implements java.io.Serializable {


    private Integer id;
    private Integer rid;
    private Integer uid;
    private String uname;
    private String telephone;
    private Integer region;
    private Integer project;
    private String content;
    private Date update;
    private Date auditdate;
    private Integer status;

    public CliReadilyTakeComment() {
    }


    public CliReadilyTakeComment(Integer id, Integer rid, Integer uid, String uname, Integer project, Date update) {
        this.id = id;
        this.rid = rid;
        this.uid = uid;
        this.uname = uname;
        this.project = project;
        this.update = update;
    }

    public CliReadilyTakeComment(Integer id, Integer rid, Integer uid, String uname, String telephone, Integer region, Integer project, String content, Date update, Date auditdate, Integer status) {
        this.id = id;
        this.rid = rid;
        this.uid = uid;
        this.uname = uname;
        this.telephone = telephone;
        this.region = region;
        this.project = project;
        this.content = content;
        this.update = update;
        this.auditdate = auditdate;
        this.status = status;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, precision = 65, scale = 30)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "rid", nullable = false, precision = 65, scale = 30)
    public Integer getRid() {
        return this.rid;
    }

    public void setRid(Integer rid) {
        this.rid = rid;
    }

    @Column(name = "uid", nullable = false, precision = 65, scale = 30)
    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    @Column(name = "uname", nullable = false, length = 50)
    public String getUname() {
        return this.uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    @Column(name = "telephone", length = 11)
    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    @Column(name = "region", precision = 65, scale = 30)
    public Integer getRegion() {
        return this.region;
    }

    public void setRegion(Integer region) {
        this.region = region;
    }

    @Column(name = "project", nullable = false, precision = 65, scale = 30)
    public Integer getProject() {
        return this.project;
    }

    public void setProject(Integer project) {
        this.project = project;
    }

    @Column(name = "content")
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update", nullable = false, length = 19)
    public Date getUpdate() {
        return this.update;
    }

    public void setUpdate(Date update) {
        this.update = update;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "auditdate", length = 19)
    public Date getAuditdate() {
        return this.auditdate;
    }

    public void setAuditdate(Date auditdate) {
        this.auditdate = auditdate;
    }

    @Column(name = "status", precision = 65, scale = 30)
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }


}


