package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


/**
 * Community generated by hbm2java
 */
public class CommunityIn implements java.io.Serializable {


    private Integer gid;
    private Integer uid;
    private String groupname;
    private String groupdescribe;
    private Integer isaudit;
    /**
	 * @return the isaudit
	 */
	public Integer getIsaudit() {
		return isaudit;
	}
	/**
	 * @param isaudit the isaudit to set
	 */
	public void setIsaudit(Integer isaudit) {
		this.isaudit = isaudit;
	}
	private Integer grouptype;
	/**
	 * @return the gid
	 */
	public Integer getGid() {
		return gid;
	}
	/**
	 * @param gid the gid to set
	 */
	public void setGid(Integer gid) {
		this.gid = gid;
	}
	/**
	 * @return the uid
	 */
	public Integer getUid() {
		return uid;
	}
	/**
	 * @param uid the uid to set
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}
	/**
	 * @return the groupname
	 */
	public String getGroupname() {
		return groupname;
	}
	/**
	 * @param groupname the groupname to set
	 */
	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}
	/**
	 * @return the groupdescribe
	 */
	public String getGroupdescribe() {
		return groupdescribe;
	}
	/**
	 * @param groupdescribe the groupdescribe to set
	 */
	public void setGroupdescribe(String groupdescribe) {
		this.groupdescribe = groupdescribe;
	}
	/**
	 * @return the grouptype
	 */
	public Integer getGrouptype() {
		return grouptype;
	}
	/**
	 * @param grouptype the grouptype to set
	 */
	public void setGrouptype(Integer grouptype) {
		this.grouptype = grouptype;
	}
   
    
    

}


