package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name = "DEPT")
public class Dept implements java.io.Serializable {


    private int deptno;
    private String dname;
    private String loc;
    private Set<Emp> emps = new HashSet<Emp>(0);

    public Dept() {
    }


    public Dept(int deptno) {
        this.deptno = deptno;
    }

    public Dept(int deptno, String dname, String loc, Set<Emp> emps) {
        this.deptno = deptno;
        this.dname = dname;
        this.loc = loc;
        this.emps = emps;
    }

    @Id

    @Column(name = "DEPTNO", unique = true, nullable = false, precision = 2, scale = 0)
    public int getDeptno() {
        return this.deptno;
    }

    public void setDeptno(int deptno) {
        this.deptno = deptno;
    }

    @Column(name = "DNAME", length = 14)
    public String getDname() {
        return this.dname;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }

    @Column(name = "LOC", length = 13)
    public String getLoc() {
        return this.loc;
    }

    public void setLoc(String loc) {
        this.loc = loc;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dept")
    public Set<Emp> getEmps() {
        return this.emps;
    }

    public void setEmps(Set<Emp> emps) {
        this.emps = emps;
    }


}


