package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "EMP")
public class Emp implements java.io.Serializable {


    private int empno;
    private Dept dept;
    private String ename;
    private String job;
    private int mgr;
    private Date hiredate;
    private int sal;
    private int comm;

    public Emp() {
    }


    public Emp(int empno) {
        this.empno = empno;
    }

    public Emp(int empno, Dept dept, String ename, String job, int mgr, Date hiredate, int sal, int comm) {
        this.empno = empno;
        this.dept = dept;
        this.ename = ename;
        this.job = job;
        this.mgr = mgr;
        this.hiredate = hiredate;
        this.sal = sal;
        this.comm = comm;
    }

    @Id

    @Column(name = "EMPNO", unique = true, nullable = false, precision = 4, scale = 0)
    public int getEmpno() {
        return this.empno;
    }

    public void setEmpno(int empno) {
        this.empno = empno;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DEPTNO")
    public Dept getDept() {
        return this.dept;
    }

    public void setDept(Dept dept) {
        this.dept = dept;
    }

    @Column(name = "ENAME", length = 10)
    public String getEname() {
        return this.ename;
    }

    public void setEname(String ename) {
        this.ename = ename;
    }

    @Column(name = "JOB", length = 9)
    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    @Column(name = "MGR", precision = 4, scale = 0)
    public int getMgr() {
        return this.mgr;
    }

    public void setMgr(int mgr) {
        this.mgr = mgr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "HIREDATE", length = 19)
    public Date getHiredate() {
        return this.hiredate;
    }

    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    @Column(name = "SAL", precision = 7)
    public int getSal() {
        return this.sal;
    }

    public void setSal(int sal) {
        this.sal = sal;
    }

    @Column(name = "COMM", precision = 7)
    public int getComm() {
        return this.comm;
    }

    public void setComm(int comm) {
        this.comm = comm;
    }


}


