package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parameter generated by hbm2java
 */
@Entity
@Table(name = "parameter")
public class Parameter implements java.io.Serializable {


    private int id;
    private String parname;
    private int parvalue;

    public Parameter() {
    }

    public Parameter(int id, String parname, int parvalue) {
        this.id = id;
        this.parname = parname;
        this.parvalue = parvalue;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, precision = 65, scale = 30)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "parname", nullable = false, length = 20)
    public String getParname() {
        return this.parname;
    }

    public void setParname(String parname) {
        this.parname = parname;
    }

    @Column(name = "parvalue", nullable = false, precision = 65, scale = 30)
    public int getParvalue() {
        return this.parvalue;
    }

    public void setParvalue(int parvalue) {
        this.parvalue = parvalue;
    }


}


