package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * Salgrade generated by hbm2java
 */
@Entity
@Table(name = "SALGRADE")
public class Salgrade implements java.io.Serializable {


    private SalgradeId id;

    public Salgrade() {
    }

    public Salgrade(SalgradeId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "grade", column = @Column(name = "GRADE", precision = 65, scale = 30)),
            @AttributeOverride(name = "losal", column = @Column(name = "LOSAL", precision = 65, scale = 30)),
            @AttributeOverride(name = "hisal", column = @Column(name = "HISAL", precision = 65, scale = 30))})
    public SalgradeId getId() {
        return this.id;
    }

    public void setId(SalgradeId id) {
        this.id = id;
    }


}


