package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SalgradeId generated by hbm2java
 */
@Embeddable
public class SalgradeId implements java.io.Serializable {


    private int grade;
    private int losal;
    private int hisal;

    public SalgradeId() {
    }

    public SalgradeId(int grade, int losal, int hisal) {
        this.grade = grade;
        this.losal = losal;
        this.hisal = hisal;
    }


    @Column(name = "GRADE", precision = 65, scale = 30)
    public int getGrade() {
        return this.grade;
    }

    public void setGrade(int grade) {
        this.grade = grade;
    }

    @Column(name = "LOSAL", precision = 65, scale = 30)
    public int getLosal() {
        return this.losal;
    }

    public void setLosal(int losal) {
        this.losal = losal;
    }

    @Column(name = "HISAL", precision = 65, scale = 30)
    public int getHisal() {
        return this.hisal;
    }

    public void setHisal(int hisal) {
        this.hisal = hisal;
    }


}


