package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysEventCallTheme generated by hbm2java
 */
@Entity
@Table(name = "sysEventCallTheme")
public class SysEventCallTheme implements java.io.Serializable {


    private Integer id;
    private Integer parentid;
    private String typename;
    private String describe;
    private Integer status;

    public SysEventCallTheme() {
    }


    public SysEventCallTheme(Integer id, Integer parentid, String typename, Integer status) {
        this.id = id;
        this.parentid = parentid;
        this.typename = typename;
        this.status = status;
    }

    public SysEventCallTheme(Integer id, Integer parentid, String typename, String describe, Integer status) {
        this.id = id;
        this.parentid = parentid;
        this.typename = typename;
        this.describe = describe;
        this.status = status;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, precision = 65, scale = 30)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "parentid", nullable = false, precision = 65, scale = 30)
    public Integer getParentid() {
        return this.parentid;
    }

    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    @Column(name = "typename", nullable = false, length = 10)
    public String getTypename() {
        return this.typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    @Column(name = "describe", length = 200)
    public String getDescribe() {
        return this.describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    @Column(name = "status", nullable = false, precision = 65, scale = 30)
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }


}


