package cn.ruihe.aluses.entity;
// Generated 2015-7-15 10:57:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysReadilyTtake generated by hbm2java
 */
@Entity
@Table(name = "sysReadilyTtake")
public class SysReadilyTtake implements java.io.Serializable {


    private Integer id;
    private int parentid = 0;
    private String typename;
    private String describe;
    private int status;
    private String color;

    public SysReadilyTtake() {
    }


    public SysReadilyTtake(int id, String typename, int status) {
        this.id = id;
        this.typename = typename;
        this.status = status;
    }

    public SysReadilyTtake(int id, int parentid, String typename, String describe, int status, String color) {
        this.id = id;
        this.parentid = parentid;
        this.typename = typename;
        this.describe = describe;
        this.status = status;
        this.color = color;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, precision = 7, scale = 0)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "parentid", precision = 7, scale = 0)
    public int getParentid() {
        return this.parentid;
    }

    public void setParentid(int parentid) {
        this.parentid = parentid;
    }

    @Column(name = "typename", nullable = false, length = 12)
    public String getTypename() {
        return this.typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    @Column(name = "describe", length = 200)
    public String getDescribe() {
        return this.describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    @Column(name = "status", nullable = false, precision = 7, scale = 0)
    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Column(name = "color", length = 10)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }


}


